FROM jenkins/jenkins:lts as jenkins-master

USER root

# ติดตั้งแพ็กเกจที่จำเป็น ได้แก่ git, curl, maven, docker, sudo และ Docker Compose v2
RUN apt-get update && apt-get install -y \
    git \
    curl \
    maven \
    docker.io \
    sudo \
    lsb-release \
    ca-certificates \
    apt-transport-https \
    gnupg \
    && apt-get clean

# ติดตั้ง Docker Compose v2 ผ่าน Docker CLI plugin
RUN curl -fsSL https://get.docker.com | sh
RUN apt-get install docker-compose-plugin

# ตรวจสอบว่า Docker Compose v2 ติดตั้งสำเร็จ
RUN docker compose version

USER jenkins